###### CREATION OF TWO CUSTOM LAYERS IN TENSORFLOW

In [1]:
#powerful library for building and training machine learning models
import tensorflow as tf

In [2]:
#define two custom layers, one for addition (AddLayer) and one for multiplication (MultiplyLayer).
#These layers perform basic mathematical operations on their inputs.

class CustomAddLayer(tf.keras.layers.Layer):
    def __init__(self, name='custom_add_layer', **kwargs):
        super(CustomAddLayer, self).__init__(name=name, **kwargs)

    def build(self, input_shape):
        # No additional weights or trainable parameters needed for addition
        super(CustomAddLayer, self).build(input_shape)

    def call(self, inputs, **kwargs):
        # Element-wise addition
        return tf.add(inputs[0], inputs[1])

    def get_config(self):
        config = super(CustomAddLayer, self).get_config()
        return config

class CustomMultiplyLayer(tf.keras.layers.Layer):
    def __init__(self, name='custom_multiply_layer', **kwargs):
        super(CustomMultiplyLayer, self).__init__(name=name, **kwargs)

    def build(self, input_shape):
        # No additional weights or trainable parameters needed for multiplication
        super(CustomMultiplyLayer, self).build(input_shape)

    def call(self, inputs, **kwargs):
        # Element-wise multiplication
        return tf.multiply(inputs[0], inputs[1])

    def get_config(self):
        config = super(CustomMultiplyLayer, self).get_config()
        return config

# Example usage:
input_a = tf.keras.layers.Input(shape=(10,), name='input_a')
input_b = tf.keras.layers.Input(shape=(10,), name='input_b')

# Adding custom layers
add_result = CustomAddLayer(name='custom_add')([input_a, input_b])
multiply_result = CustomMultiplyLayer(name='custom_multiply')([input_a, input_b])

# Creating models
add_model = tf.keras.Model(inputs=[input_a, input_b], outputs=add_result, name='addition_model')
multiply_model = tf.keras.Model(inputs=[input_a, input_b], outputs=multiply_result, name='multiplication_model')

# Displaying model summaries
add_model.summary()
multiply_model.summary()


Model: "addition_model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_a (InputLayer)        [(None, 10)]                 0         []                            
                                                                                                  
 input_b (InputLayer)        [(None, 10)]                 0         []                            
                                                                                                  
 custom_add (CustomAddLayer  (None, 10)                   0         ['input_a[0][0]',             
 )                                                                   'input_b[0][0]']             
                                                                                                  
Total params: 0 (0.00 Byte)
Trainable params: 0 (0.00 Byte)
Non-trainable params: 0 (

######  COMMBINATION OF TWO LAYERS IN A THIRD CUSTOM LAYER

In [3]:
# Combination of  these two layers in a third custom layer. Concatenate them or multiply them
class CustomCombineLayer(tf.keras.layers.Layer):
    def __init__(self, name='custom_combine_layer', **kwargs):
        super(CustomCombineLayer, self).__init__(name=name, **kwargs)

    def build(self, input_shape):
        # No additional weights or trainable parameters needed for combination
        super(CustomCombineLayer, self).build(input_shape)

    def call(self, inputs, **kwargs):
        add_output = inputs[0]
        multiply_output = inputs[1]

        # Concatenate the outputs along the last axis (axis=-1)
        combined_output = tf.concat([add_output, multiply_output], axis=-1)

        return combined_output

    def get_config(self):
        config = super(CustomCombineLayer, self).get_config()
        return config

# Example usage:
input_a = tf.keras.layers.Input(shape=(10,), name='input_a')
input_b = tf.keras.layers.Input(shape=(10,), name='input_b')

# Adding custom layers
add_result = CustomAddLayer(name='custom_add')([input_a, input_b])
multiply_result = CustomMultiplyLayer(name='custom_multiply')([input_a, input_b])

# Combine custom layers using the third custom layer
combined_result = CustomCombineLayer(name='custom_combine')([add_result, multiply_result])

# Creating model
combined_model = tf.keras.Model(inputs=[input_a, input_b], outputs=combined_result, name='combined_model')

# Displaying model summary
combined_model.summary()


Model: "combined_model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_a (InputLayer)        [(None, 10)]                 0         []                            
                                                                                                  
 input_b (InputLayer)        [(None, 10)]                 0         []                            
                                                                                                  
 custom_add (CustomAddLayer  (None, 10)                   0         ['input_a[0][0]',             
 )                                                                   'input_b[0][0]']             
                                                                                                  
 custom_multiply (CustomMul  (None, 10)                   0         ['input_a[0][0]',

###### CREATE A MODEL AND OBSERVE WORKING OF BATCH INFERENCE

In [4]:
import numpy as np

# Generating random input data for batch inference
num_samples = 5
input_data_a = np.random.rand(num_samples, 10)
input_data_b = np.random.rand(num_samples, 10)

# Performing batch inference
predictions = combined_model.predict([input_data_a, input_data_b])

# Displaying predictions
print("Input Data A:")
print(input_data_a)
print("\nInput Data B:")
print(input_data_b)
print("\nPredictions:")
print(predictions)

1/1 [==============================] - 0s 386ms/step
Input Data A:
[[5.47663010e-01 1.15408703e-02 2.97959456e-01 8.62817715e-01
  3.23037386e-01 7.88809179e-02 1.50127267e-01 7.01642161e-01
  5.40703643e-01 7.58603524e-01]
 [1.46031640e-01 7.26376017e-01 1.29225607e-01 7.91798559e-01
  3.30847765e-01 9.37856242e-01 8.11248222e-02 4.84631185e-01
  1.32648690e-01 1.75552140e-01]
 [9.75075589e-01 3.27718277e-01 7.41454458e-01 8.93303360e-01
  8.66129356e-01 5.82422234e-01 6.44035308e-01 3.19852439e-02
  6.51189577e-01 1.25405941e-01]
 [3.49154310e-01 6.93716960e-02 3.70893829e-02 7.52512071e-01
  2.92611278e-01 1.59475870e-01 1.48923400e-01 7.17888784e-01
  7.70432230e-01 9.64849477e-04]
 [8.46723234e-01 6.94034274e-01 9.29336363e-01 5.57503154e-01
  9.10085153e-01 9.73873335e-01 4.03440250e-01 4.74969127e-01
  7.93314529e-01 4.08557161e-01]]

Input Data B:
[[0.4620052  0.83813497 0.31789454 0.03236751 0.62853236 0.53764737
  0.52758798 0.68615416 0.33593994 0.02549692]
 [0.46205322 0.12

###### SPLITTING OF INPUT IMAGE INTO 4*4 TILES

In [5]:

# Example input image
input_image = tf.keras.layers.Input(shape=(None, None, 3))  # Assuming RGB image

# Define the size of the tiles
tile_size = (4, 4, 3)  # Height, Width, Channels

# Use tf.image.extract_patches to split the image into tiles
tiles = tf.image.extract_patches(
    input_image,
    sizes=[1, tile_size[0], tile_size[1], 1],  # Batch, Height, Width, Channels
    strides=[1, tile_size[0], tile_size[1], 1],  # Batch, Height, Width, Channels
    rates=[1, 1, 1, 1],  # Batch, Height, Width, Channels
    padding='VALID'
)

# Reshape the tiles to have the desired shape (4x4 tiles)
tiles = tf.reshape(tiles, (-1, tile_size[0], tile_size[1], tile_size[2]))

# Creating a model to visualize the result
model = tf.keras.Model(inputs=input_image, outputs=tiles)
model.summary()

# Example usage with a random image
random_image = tf.random.normal((1, 16, 16, 3))  # Assuming a 16x16 RGB image
result_tiles = model.predict(random_image)

# Displaying the result
print("Input Image:")
print(random_image.numpy().squeeze().astype(int))
print("\nResult Tiles:")
print(result_tiles.astype(int))

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, None, None, 3)]   0         
                                                                 
 tf.image.extract_patches (  (None, None, None, 48)    0         
 TFOpLambda)                                                     
                                                                 
 tf.reshape (TFOpLambda)     (None, 4, 4, 3)           0         
                                                                 
Total params: 0 (0.00 Byte)
Trainable params: 0 (0.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
1/1 [==============================] - 0s 54ms/step
Input Image:
[[[ 0  2  0]
  [-1  1 -2]
  [-1  2  1]
  [-1 -1  0]
  [ 0 -1  0]
  [ 1 -1  0]
  [ 1 -1 -1]
  [ 1  0 -1]
  [ 0  0  0]
  [ 0  0  1]
  [ 0 -1  0]
  [ 0  0  0]
  [ 0  1

###### GRAPH DATA STRUCTURE

In [6]:
import random

class Graph:
    def __init__(self):
        self.graph = {}

    def add_edge(self, start, end):
        if start not in self.graph:
            self.graph[start] = []
        self.graph[start].append(end)

    def generate_random_connections(self, nodes, num_connections):
        for _ in range(num_connections):
            start = random.choice(nodes)
            end = random.choice(nodes)
            self.add_edge(start, end)

    def display_graph(self):
        for node, neighbors in self.graph.items():
            print(f"{node} -> {', '.join(neighbors)}")

# Example usage
nodes = ['A', 'B', 'C', 'D', 'E']
num_connections = 7

graph = Graph()
graph.generate_random_connections(nodes, num_connections)

print("Random Graph:")
graph.display_graph()

Random Graph:
B -> B, D, C
D -> C
E -> A, C
A -> A


In [7]:
# Custom Node Class
class GraphNode:
    def __init__(self, name, model):
        self.name = name
        self.model = model

    def apply_inference_rule(self, input_data):
        # Convert input data to NumPy arrays
        input_a = np.array(input_data[0])
        input_b = np.array(input_data[1])

        # Apply inference rule based on the output
        output = self.model.predict([input_a, input_b])
        
        # Assuming output is a NumPy array, access the first element
        output_value = output[0]

        if output_value > 50:
            return "High_Output_Node"
        elif output_value < 50:
            return "Low_Output_Node"
        else:
            return "Equal_Output_Node"

# Example usage
nodes = ['A', 'B', 'C', 'D', 'E']

# Create a graph with random connections
graph = Graph()
graph.generate_random_connections(nodes, 7)

# Create a model using the CustomAddLayer
input_a = tf.keras.layers.Input(shape=(1,))
input_b = tf.keras.layers.Input(shape=(1,))
add_result = CustomAddLayer(name='custom_add')([input_a, input_b])
add_model = tf.keras.Model(inputs=[input_a, input_b], outputs=add_result)

# Create nodes with custom models
node_A = GraphNode("A", add_model)
node_B = GraphNode("B", add_model)
node_C = GraphNode("C", add_model)
node_D = GraphNode("D", add_model)
node_E = GraphNode("E", add_model)

# Simulate random input data for inference
random_input = random.randint(1, 100)

# Perform inference in Node A
next_node = node_A.apply_inference_rule([[random_input], [random_input]])

# Display the result
print(f"Initial Random Input: {random_input}")
print(f"Node A Output: {add_model.predict([np.array([[random_input]]), np.array([[random_input]])])[0][0]}")
print(f"Next Node: {next_node}")



1/1 [==============================] - 0s 72ms/step
Initial Random Input: 90
1/1 [==============================] - 0s 81ms/step
Node A Output: 180.0
Next Node: High_Output_Node


###### OBJECT DETTECTION MODELS

In [29]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=FutureWarning)


In [40]:
import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models

# Paths to your train and validation datasets
train_dir = 'Train'
validation_dir = 'Valid'
img_height, img_width = 224, 224
batch_size = 20

# Create image data generators
train_datagen = ImageDataGenerator(rescale=1./255)
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical'
)

validation_datagen = ImageDataGenerator(rescale=1./255)
validation_generator = validation_datagen.flow_from_directory(
    validation_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical'
)

# Load pre-trained MobileNetV2 model without top classification layer
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(img_height, img_width, 3))

# Freeze the base model layers
base_model.trainable = False

# Create a new model on top
model1 = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(len(train_generator.class_indices), activation='softmax')
])

# Compile the model
model1.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train the model
model1.fit(
    train_generator,
    epochs=3,
    validation_data=validation_generator
)


Found 900 images belonging to 6 classes.
Found 39 images belonging to 6 classes.
Epoch 1/3
45/45 [==============================] - 107s 2s/step - loss: 1.1908 - accuracy: 0.5922 - val_loss: 1.0807 - val_accuracy: 0.6410
Epoch 2/3
45/45 [==============================] - 97s 2s/step - loss: 0.4568 - accuracy: 0.8378 - val_loss: 1.0258 - val_accuracy: 0.6410
Epoch 3/3
45/45 [==============================] - 97s 2s/step - loss: 0.2856 - accuracy: 0.9044 - val_loss: 1.0878 - val_accuracy: 0.6154


In [38]:
import tensorflow as tf
from tensorflow.keras.applications import InceptionV3
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models

# Paths to your train and validation datasets
train_dir = 'Train'
validation_dir = 'Valid'
img_height, img_width = 299, 299  # InceptionV3 requires input size of (299, 299)
batch_size = 25

# Create image data generators
train_datagen = ImageDataGenerator(rescale=1./255)
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical'
)

validation_datagen = ImageDataGenerator(rescale=1./255)
validation_generator = validation_datagen.flow_from_directory(
    validation_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical'
)

# Load pre-trained InceptionV3 model without top classification layer
base_model = InceptionV3(weights='imagenet', include_top=False, input_shape=(img_height, img_width, 3))

# Freeze the base model layers
base_model.trainable = False

# Create a new model on top
model2 = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(len(train_generator.class_indices), activation='softmax')
])

# Compile the model
model2.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train the model
model2.fit(
    train_generator,
    epochs=3,
    validation_data=validation_generator
)


Found 900 images belonging to 6 classes.
Found 39 images belonging to 6 classes.
87910968/87910968 [==============================] - 12s 0us/step
Epoch 1/3
36/36 [==============================] - 1373s 38s/step - loss: 1.2410 - accuracy: 0.5389 - val_loss: 0.8535 - val_accuracy: 0.7692
Epoch 2/3
36/36 [==============================] - 1350s 38s/step - loss: 0.6216 - accuracy: 0.7778 - val_loss: 0.7757 - val_accuracy: 0.7949
Epoch 3/3
36/36 [==============================] - 1242s 35s/step - loss: 0.3920 - accuracy: 0.8756 - val_loss: 0.7708 - val_accuracy: 0.8205


###### MobileNetV2 & InceptionV3

###### QUANTIZED MODEL FOR MobileNet V2

In [46]:
# Convert the model to a quantized model 
converter = tf.lite.TFLiteConverter.from_keras_model(model1)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
quantized_model1 = converter.convert()

# Save the quantized model to a file
with open('quantized_model.tflite', 'wb') as f:
    f.write(quantized_model1)


Cause: Unable to locate the source code of <function trace_model_call.<locals>._wrapped_model at 0x00000246F1069080>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Cause: Unable to locate the source code of <function trace_model_call.<locals>._wrapped_model at 0x00000246F1069080>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Cause: Unable to locate the source code of <function trace_model_call.<locals>._wrapped_model at 0x00000246F1069080>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


INFO:absl:Function `_wrapped_model` contains input name(s) mobilenetv2_1.00_224_input, resource with unsupported characters which will be renamed to mobilenetv2_1_00_224_input, sequential_3_dense_7_biasadd_readvariableop_resource in the SavedModel.


Cause: Unable to locate the source code of <function canonicalize_signatures.<locals>.signature_wrapper at 0x000002470219BCE0>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Cause: Unable to locate the source code of <function canonicalize_signatures.<locals>.signature_wrapper at 0x000002470219BCE0>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Cause: Unable to locate the source code of <function canonicalize_signatures.<locals>.signature_wrapper at 0x000002470219BCE0>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


INFO:absl:Found untraced functions such as _update_step_xla, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 53). These functions will not be directly callable after loading.


INFO:tensorflow:Assets written to: C:\Users\user\AppData\Local\Temp\tmpja9rd231\assets


INFO:tensorflow:Assets written to: C:\Users\user\AppData\Local\Temp\tmpja9rd231\assets
INFO:absl:Writing fingerprint to C:\Users\user\AppData\Local\Temp\tmpja9rd231\fingerprint.pb
INFO:absl:Using new converter: If you encounter a problem please file a bug. You can opt-out by setting experimental_new_converter=False


In [51]:
import numpy as np
from PIL import Image
import os

# Paths to your test dataset
test_dir = 'Valid'  # Replace with the actual path to your test dataset

# Create an image data generator for the test dataset
test_datagen = ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(img_height, img_width),
    batch_size=1,  # Set batch_size to 1 for inference on individual images
    class_mode='categorical',
    shuffle=False  # Ensure the order of predictions matches the order of images
)

# Load the quantized TFLite model
interpreter = tf.lite.Interpreter(model_content=quantized_model1)
interpreter.allocate_tensors()

# Get input and output details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Perform inference on each image in the test dataset
all_predictions = []

ground_truth_labels = test_generator.classes  # Ground truth labels (integer classes)

for i in range(len(test_generator.filenames)):
    # Load an image for inference
    image_path = os.path.join(test_dir, test_generator.filenames[i])
    image = Image.open(image_path).resize((img_width, img_height))
    image = np.array(image) / 255.0  # Normalize the image

    # Prepare the input data
    input_data = np.expand_dims(image, axis=0).astype(input_details[0]['dtype'])
    interpreter.set_tensor(input_details[0]['index'], input_data)

    # Run inference
    interpreter.invoke()

    # Get the output
    output_data = interpreter.get_tensor(output_details[0]['index'])
    predicted_class = np.argmax(output_data)
    all_predictions.append(predicted_class)

# Calculate accuracy
correct_predictions = np.sum(np.array(all_predictions) == ground_truth_labels)
total_samples = len(ground_truth_labels)
accuracy = correct_predictions / total_samples

# Print or use the accuracy as needed
print("Accuracy:", accuracy)


Found 39 images belonging to 6 classes.
Accuracy: 0.6410256410256411


###### QUANTIZED MODEL FOR Inception V3

In [58]:


# Convert the new model to TensorFlow Lite format
converter = tf.lite.TFLiteConverter.from_keras_model(model2)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
quantized_model2 = converter.convert()

# Save the quantized model to a file
with open('quantized_model2.tflite', 'wb') as f:
    f.write(quantized_model2)


AttributeError: 'RetinaNet' object has no attribute 'call'

In [59]:
from tflite_model_maker import model_spec
from tflite_model_maker import image_classifier

model_spec = model_spec.ImageModelSpec.from_keras_model(model2)
image_classifier.create(model_spec, train_data=train_generator, validation_data=validation_generator)
quantized_model2 = model_spec.create_tflite(quantization_config='dr')

# Save the quantized model to a file
with open('quantized_model2.tflite', 'wb') as f:
    f.write(quantized_model2)

ModuleNotFoundError: No module named 'tflite_model_maker'

In [ ]:
import numpy as np
from PIL import Image
import os

# Paths to your test dataset
test_dir = 'Valid'  # Replace with the actual path to your test dataset

# Create an image data generator for the test dataset
test_datagen = ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(img_height, img_width),
    batch_size=1,  # Set batch_size to 1 for inference on individual images
    class_mode='categorical',
    shuffle=False  # Ensure the order of predictions matches the order of images
)

# Load the quantized TFLite model
interpreter = tf.lite.Interpreter(model_content=quantized_model2)
interpreter.allocate_tensors()

# Get input and output details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Perform inference on each image in the test dataset
all_predictions = []

ground_truth_labels = test_generator.classes  # Ground truth labels (integer classes)

for i in range(len(test_generator.filenames)):
    # Load an image for inference
    image_path = os.path.join(test_dir, test_generator.filenames[i])
    image = Image.open(image_path).resize((img_width, img_height))
    image = np.array(image) / 255.0  # Normalize the image

    # Prepare the input data
    input_data = np.expand_dims(image, axis=0).astype(input_details[0]['dtype'])
    interpreter.set_tensor(input_details[0]['index'], input_data)

    # Run inference
    interpreter.invoke()

    # Get the output
    output_data = interpreter.get_tensor(output_details[0]['index'])
    predicted_class = np.argmax(output_data)
    all_predictions.append(predicted_class)

# Calculate accuracy
correct_predictions = np.sum(np.array(all_predictions) == ground_truth_labels)
total_samples = len(ground_truth_labels)
accuracy = correct_predictions / total_samples

# Print or use the accuracy as needed
print("Accuracy:", accuracy)


###### DIFFERENCES